-- =========================
-- 테이블 생성
-- =========================

SET search_path TO public;

-- BMS 테이블
CREATE TABLE IF NOT EXISTS bongo3_bms_data (
    device_no VARCHAR,
    measured_month VARCHAR,
    time VARCHAR,
    msg_time VARCHAR,
    acceptable_chrg_pw NUMERIC,
    acceptable_dischrg_pw NUMERIC,
    airbag_hwire_duty NUMERIC,
    batt_coolant_inlet_temp NUMERIC,
    batt_fan_running NUMERIC,
    batt_internal_temp NUMERIC,
    batt_ltr_rear_temp NUMERIC,
    batt_pra_busbar_temp NUMERIC,
    batt_pw NUMERIC,
    bms_running NUMERIC,
    cellvolt_dispersion NUMERIC,
    -- 개별 셀 전압 (192개)
    cell_volt_1 NUMERIC, cell_volt_2 NUMERIC, cell_volt_3 NUMERIC, cell_volt_4 NUMERIC, cell_volt_5 NUMERIC,
    cell_volt_6 NUMERIC, cell_volt_7 NUMERIC, cell_volt_8 NUMERIC, cell_volt_9 NUMERIC, cell_volt_10 NUMERIC,
    cell_volt_11 NUMERIC, cell_volt_12 NUMERIC, cell_volt_13 NUMERIC, cell_volt_14 NUMERIC, cell_volt_15 NUMERIC,
    cell_volt_16 NUMERIC, cell_volt_17 NUMERIC, cell_volt_18 NUMERIC, cell_volt_19 NUMERIC, cell_volt_20 NUMERIC,
    cell_volt_21 NUMERIC, cell_volt_22 NUMERIC, cell_volt_23 NUMERIC, cell_volt_24 NUMERIC, cell_volt_25 NUMERIC,
    cell_volt_26 NUMERIC, cell_volt_27 NUMERIC, cell_volt_28 NUMERIC, cell_volt_29 NUMERIC, cell_volt_30 NUMERIC,
    cell_volt_31 NUMERIC, cell_volt_32 NUMERIC, cell_volt_33 NUMERIC, cell_volt_34 NUMERIC, cell_volt_35 NUMERIC,
    cell_volt_36 NUMERIC, cell_volt_37 NUMERIC, cell_volt_38 NUMERIC, cell_volt_39 NUMERIC, cell_volt_40 NUMERIC,
    cell_volt_41 NUMERIC, cell_volt_42 NUMERIC, cell_volt_43 NUMERIC, cell_volt_44 NUMERIC, cell_volt_45 NUMERIC,
    cell_volt_46 NUMERIC, cell_volt_47 NUMERIC, cell_volt_48 NUMERIC, cell_volt_49 NUMERIC, cell_volt_50 NUMERIC,
    cell_volt_51 NUMERIC, cell_volt_52 NUMERIC, cell_volt_53 NUMERIC, cell_volt_54 NUMERIC, cell_volt_55 NUMERIC,
    cell_volt_56 NUMERIC, cell_volt_57 NUMERIC, cell_volt_58 NUMERIC, cell_volt_59 NUMERIC, cell_volt_60 NUMERIC,
    cell_volt_61 NUMERIC, cell_volt_62 NUMERIC, cell_volt_63 NUMERIC, cell_volt_64 NUMERIC, cell_volt_65 NUMERIC,
    cell_volt_66 NUMERIC, cell_volt_67 NUMERIC, cell_volt_68 NUMERIC, cell_volt_69 NUMERIC, cell_volt_70 NUMERIC,
    cell_volt_71 NUMERIC, cell_volt_72 NUMERIC, cell_volt_73 NUMERIC, cell_volt_74 NUMERIC, cell_volt_75 NUMERIC,
    cell_volt_76 NUMERIC, cell_volt_77 NUMERIC, cell_volt_78 NUMERIC, cell_volt_79 NUMERIC, cell_volt_80 NUMERIC,
    cell_volt_81 NUMERIC, cell_volt_82 NUMERIC, cell_volt_83 NUMERIC, cell_volt_84 NUMERIC, cell_volt_85 NUMERIC,
    cell_volt_86 NUMERIC, cell_volt_87 NUMERIC, cell_volt_88 NUMERIC, cell_volt_89 NUMERIC, cell_volt_90 NUMERIC,
    cell_volt_91 NUMERIC, cell_volt_92 NUMERIC, cell_volt_93 NUMERIC, cell_volt_94 NUMERIC, cell_volt_95 NUMERIC,
    cell_volt_96 NUMERIC, cell_volt_97 NUMERIC, cell_volt_98 NUMERIC, cell_volt_99 NUMERIC, cell_volt_100 NUMERIC,
    cell_volt_101 NUMERIC, cell_volt_102 NUMERIC, cell_volt_103 NUMERIC, cell_volt_104 NUMERIC, cell_volt_105 NUMERIC,
    cell_volt_106 NUMERIC, cell_volt_107 NUMERIC, cell_volt_108 NUMERIC, cell_volt_109 NUMERIC, cell_volt_110 NUMERIC,
    cell_volt_111 NUMERIC, cell_volt_112 NUMERIC, cell_volt_113 NUMERIC, cell_volt_114 NUMERIC, cell_volt_115 NUMERIC,
    cell_volt_116 NUMERIC, cell_volt_117 NUMERIC, cell_volt_118 NUMERIC, cell_volt_119 NUMERIC, cell_volt_120 NUMERIC,
    cell_volt_121 NUMERIC, cell_volt_122 NUMERIC, cell_volt_123 NUMERIC, cell_volt_124 NUMERIC, cell_volt_125 NUMERIC,
    cell_volt_126 NUMERIC, cell_volt_127 NUMERIC, cell_volt_128 NUMERIC, cell_volt_129 NUMERIC, cell_volt_130 NUMERIC,
    cell_volt_131 NUMERIC, cell_volt_132 NUMERIC, cell_volt_133 NUMERIC, cell_volt_134 NUMERIC, cell_volt_135 NUMERIC,
    cell_volt_136 NUMERIC, cell_volt_137 NUMERIC, cell_volt_138 NUMERIC, cell_volt_139 NUMERIC, cell_volt_140 NUMERIC,
    cell_volt_141 NUMERIC, cell_volt_142 NUMERIC, cell_volt_143 NUMERIC, cell_volt_144 NUMERIC, cell_volt_145 NUMERIC,
    cell_volt_146 NUMERIC, cell_volt_147 NUMERIC, cell_volt_148 NUMERIC, cell_volt_149 NUMERIC, cell_volt_150 NUMERIC,
    cell_volt_151 NUMERIC, cell_volt_152 NUMERIC, cell_volt_153 NUMERIC, cell_volt_154 NUMERIC, cell_volt_155 NUMERIC,
    cell_volt_156 NUMERIC, cell_volt_157 NUMERIC, cell_volt_158 NUMERIC, cell_volt_159 NUMERIC, cell_volt_160 NUMERIC,
    cell_volt_161 NUMERIC, cell_volt_162 NUMERIC, cell_volt_163 NUMERIC, cell_volt_164 NUMERIC, cell_volt_165 NUMERIC,
    cell_volt_166 NUMERIC, cell_volt_167 NUMERIC, cell_volt_168 NUMERIC, cell_volt_169 NUMERIC, cell_volt_170 NUMERIC,
    cell_volt_171 NUMERIC, cell_volt_172 NUMERIC, cell_volt_173 NUMERIC, cell_volt_174 NUMERIC, cell_volt_175 NUMERIC,
    cell_volt_176 NUMERIC, cell_volt_177 NUMERIC, cell_volt_178 NUMERIC, cell_volt_179 NUMERIC, cell_volt_180 NUMERIC,
    cell_volt_181 NUMERIC, cell_volt_182 NUMERIC, cell_volt_183 NUMERIC, cell_volt_184 NUMERIC, cell_volt_185 NUMERIC,
    cell_volt_186 NUMERIC, cell_volt_187 NUMERIC, cell_volt_188 NUMERIC, cell_volt_189 NUMERIC, cell_volt_190 NUMERIC,
    cell_volt_191 NUMERIC, cell_volt_192 NUMERIC,
    chrg_cable_conn NUMERIC,
    chrg_cnt NUMERIC,
    chrg_cnt_q NUMERIC,
    cumul_current_chrgd NUMERIC,
    cumul_current_dischrgd NUMERIC,
    cumul_energy_chrgd NUMERIC,
    cumul_energy_chrgd_q NUMERIC,
    cumul_pw_chrgd NUMERIC,
    cumul_pw_dischrgd NUMERIC,
    drive_motor_spd_1 NUMERIC,
    drive_motor_spd_2 NUMERIC,
    emobility_spd NUMERIC,
    est_chrg_time NUMERIC,
    ext_temp NUMERIC,
    fast_chrg_port_conn NUMERIC,
    fast_chrg_relay_on NUMERIC,
    hvac_list_1 NUMERIC,
    hvac_list_2 NUMERIC,
    insul_resistance NUMERIC,
    int_temp NUMERIC,
    inverter_capacity_volt NUMERIC,
    main_relay_conn NUMERIC,
    max_cell_volt NUMERIC,
    max_cell_volt_no NUMERIC,
    max_deter_cell_no NUMERIC,
    min_cell_volt NUMERIC,
    min_cell_volt_no NUMERIC,
    min_deter NUMERIC,
    min_deter_cell_no NUMERIC,
    mod_avg_temp NUMERIC,
    mod_max_temp NUMERIC,
    mod_min_temp NUMERIC,
    -- 개별 모듈 온도 (18개)
    mod_temp_1 NUMERIC, mod_temp_2 NUMERIC, mod_temp_3 NUMERIC, mod_temp_4 NUMERIC, mod_temp_5 NUMERIC,
    mod_temp_6 NUMERIC, mod_temp_7 NUMERIC, mod_temp_8 NUMERIC, mod_temp_9 NUMERIC, mod_temp_10 NUMERIC,
    mod_temp_11 NUMERIC, mod_temp_12 NUMERIC, mod_temp_13 NUMERIC, mod_temp_14 NUMERIC, mod_temp_15 NUMERIC,
    mod_temp_16 NUMERIC, mod_temp_17 NUMERIC, mod_temp_18 NUMERIC,
    msg_id NUMERIC,
    odometer NUMERIC,
    op_time NUMERIC,
    pack_current NUMERIC,
    pack_volt NUMERIC,
    seq NUMERIC,
    slow_chrg_port_conn NUMERIC,
    soc NUMERIC,
    socd NUMERIC,
    soh NUMERIC,
    start_time VARCHAR,
    sub_batt_volt NUMERIC,
    trip_chrg_pw NUMERIC,
    trip_dischrg_pw NUMERIC,
    v2l NUMERIC,
    car_type VARCHAR
);

CREATE TABLE IF NOT EXISTS gv60_bms_data (LIKE bongo3_bms_data);
CREATE TABLE IF NOT EXISTS porter2_bms_data (LIKE bongo3_bms_data);

-- GPS 테이블
CREATE TABLE IF NOT EXISTS bongo3_gps_data (
    device_no VARCHAR,
    time TIMESTAMP,
    direction NUMERIC,
    fuel_pct NUMERIC,
    hdop NUMERIC,
    lat NUMERIC,
    lng NUMERIC,
    mode VARCHAR,
    source VARCHAR,
    speed NUMERIC,
    state VARCHAR,
    car_type VARCHAR
);

CREATE TABLE IF NOT EXISTS gv60_gps_data (LIKE bongo3_gps_data);
CREATE TABLE IF NOT EXISTS porter2_gps_data (LIKE bongo3_gps_data);
